// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import { Document, Packer, Paragraph, Tab, TextRun } from "docx";
import { saveAs } from './FileSaver.js';

// BEGIN EXTRA CODE
function saveDocumentToFile(doc, fileName) {
	// Create a mime type that will associate the new file with Microsoft Word
	const mimeType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
	// Create a Blob object from Packer containing the Document instance and the mimeType
	Packer.toBlob(doc).then((blob) => {
		const docblob = blob.slice(0, blob.size, mimeType)
		// Save the file using saveAs from the file-saver package
		saveAs(docblob, fileName)
	})
}
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JSA_PersonList_GenerateDocx() {
	// BEGIN USER CODE
	// Simple example to add text to a document
	const doc = new Document({
		sections: [
			{
				properties: {},
				children: [
					new Paragraph({
						children: [
							new TextRun("Hello World"),
							new TextRun({
								text: "Foo Bar",
								bold: true,
								size: 40,
							}),
							new TextRun({
								children: [new Tab(), "Github is the best"],
								bold: true,
							}),
						],
					}),
				],
			},
		],
	});

	saveDocumentToFile(doc, "My Document.docx");

	// Packer.toBuffer(doc).then((buffer) => {
	// 	fs.writeFileSync("My Document.docx", buffer);
	// });
	// END USER CODE
}
