// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import { faker } from '@faker-js/faker';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} count
 * @returns {Promise.<MxObject[]>}
 */
export async function JSA_Person_CreateNFakePersons(count) {
	// BEGIN USER CODE
	const randomName = faker.person.fullName(); 
	console.log(randomName);
	// END USER CODE
}
