// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import { faker } from '@faker-js/faker';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {Big} count
 * @returns {Promise.<string>}
 */
export async function JSA_Person_CreateNFakePersons(count) {
	// BEGIN USER CODE
	const fakePersonList = [];

	for(var it = 0; it < count; it++){
		fakePersonList.push({
			firstName: faker.person.firstName(),
			lastName: faker.person.lastName(),
			gender: faker.person.sex(),
			jobTitle: faker.person.jobTitle(),
			age: faker.number.int({ min: 18, max: 68 })
		});
	}
	let fakePersonListAsJson = JSON.stringify(fakePersonList);
	console.info(fakePersonListAsJson);
	return fakePersonListAsJson;
	
	// END USER CODE
}
